default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: <%= ENV.fetch("PGDATABASE") { "evalia_development" } %>
  username: <%= ENV.fetch("PGUSER") { "postgres" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>

test:
  <<: *default
  database: evalia_test

production:
  <<: *default