class LessonPlan < ApplicationRecord
  belongs_to :teacher
  belongs_to :course, foreign_key: 'class_id', optional: true
  
  has_many :lesson_plan_materials, dependent: :destroy
  has_many :lesson_plan_generated_contents, dependent: :destroy
  
  has_rich_text :content
  
  # Validations
  validates :title, presence: true
  validates :teacher_id, presence: true
  
  # Scopes
  scope :recent, -> { order(created_at: :desc) }
  scope :by_teacher, ->(teacher_id) { where(teacher_id: teacher_id) }
  scope :by_course, ->(course_id) { where(class_id: course_id) }
  
  # Methods
  def material_count
    lesson_plan_materials.count
  end
  
  def has_materials?
    material_count > 0
  end
  
  def generate_content_for(content_type)
    # Integration point for OpenAI
    # This would normally call OpenAI to generate content
    # For now, we'll create a placeholder
    generated_content = lesson_plan_generated_contents.create!(
      content_type: content_type,
      status: 'generated',
      content: "This is a placeholder for #{content_type} content that would be generated by OpenAI.",
      is_applied: false
    )
    
    generated_content
  end
  
  def apply_generated_content(content_id)
    generated_content = lesson_plan_generated_contents.find(content_id)
    
    # Skip if already applied
    return generated_content if generated_content.is_applied
    
    # Apply the content to the lesson plan
    case generated_content.content_type
    when 'learning_objectives'
      update(learning_objectives: generated_content.content)
    when 'activities'
      update(activities: generated_content.content)
    when 'assessment'
      update(assessment: generated_content.content)
    when 'resources'
      update(resources: generated_content.content)
    when 'full_plan'
      # Update all sections
      update(
        learning_objectives: generated_content.content,
        activities: generated_content.content,
        assessment: generated_content.content,
        resources: generated_content.content
      )
    end
    
    # Mark as applied
    generated_content.update(is_applied: true)
    
    generated_content
  end
  
  def export_to_docx
    # Integration point for document generation
    # This would generate a DOCX file using a gem like docx
    # For now, we'll return a placeholder path
    "lesson_plan_#{id}.docx"
  end
  
  def export_to_pdf
    # Integration point for PDF generation
    # This would generate a PDF file using a gem like prawn or wicked_pdf
    # For now, we'll return a placeholder path
    "lesson_plan_#{id}.pdf"
  end
end